name: Build and Release

on:
  push:
    tags:
      - "V*"
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: "BatterySimulator.sln"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BUILD_CONFIGURATION: Debug

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      with:
        msbuild-architecture: x64
        
    - name: Build Solution
      run: msbuild ${{ env.SOLUTION_FILE_PATH }} /p:Configuration=${{ env.BUILD_CONFIGURATION }}
      
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload batteryconfig.exe to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: D:\a\Battery-Driver_Hub\Battery-Driver_Hub\x64\Debug\batteryconfig.exe
        asset_name: batteryconfig.exe
        asset_content_type: application/octet-stream

    - name: Compress Simbatt Folder
      run: |
        Compress-Archive -Path "D:\a\Battery-Driver_Hub\Battery-Driver_Hub\x64\Debug\simbatt" -DestinationPath "D:\a\Battery-Driver_Hub\Battery-Driver_Hub\x64\Debug\simbatt.zip"
    
    - name: Upload Simbatt Folder as Zip to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: D:\a\Battery-Driver_Hub\Battery-Driver_Hub\x64\Debug\simbatt.zip
        asset_name: simbatt.zip
        asset_content_type: application/zip
