# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: "BatterySimulator.sln"

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
     
        
    - name: check Secure Boot
      shell: pwsh
      run: ./check_secure_boot.ps1

        

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        msbuild-architecture: x64

    - name: Run script to check Secure Boot
      shell: powershell
      run: ./check_secure_boot.ps1
      
    - name: Disable Secure Boot
      if: steps.secure_boot.outputs.secure_boot == 'enabled'
      shell: pwsh
      run: |
        bcdedit /set testsigning off
        bcdedit /set nointegritychecks off
        shutdown /r /f /t 
          
    - name: Enable test-signed drivers
      shell: pwsh
      run: |
        bcdedit /set testsigning on
        
    - name: Run INSTALL.bat as Administrator
      shell: pwsh
      run: ./Install_Driver.ps1
        
